server {
    listen 80;
    server_name ${SERVER_NAME};

    client_max_body_size ${CLIENT_MAX_BODY_SIZE};

    # Serve Frontend Static Files
    location / {
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Proxy API Requests to Backend API
    location /api/ {
        proxy_pass http://backend_api:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Handle WebSocket connections if needed
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    # Deny Access to .env Files
    location ~ /\.env {
        deny all;
    }

    # Security Headers for HTTP (Limited)
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header X-Referrer-Policy "strict-origin-when-cross-origin" always;
    
    # Updated Content Security Policy without 'unsafe-inline'
    add_header Content-Security-Policy "default-src 'self'; \
        script-src 'self' https://biowasm.com; \
        style-src 'self'; \
        img-src 'self' data:; \
        object-src 'none'; \
        frame-ancestors 'self'; \
        base-uri 'self'; \
        form-action 'self';" always;

    add_header Cross-Origin-Resource-Policy "same-origin" always;

    # Hide Nginx version
    server_tokens off;

    # Serve ACME challenge
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
}
